/**
 * @fileoverview Default Handlebars templates for Markdown documentation rendering.
 * Layer 1 module - no imports (pure string constants).
 * @module core/renderer/templates
 */

/** Template for rendering a complete module documentation page. */
export const moduleTemplate = `# {{module.path}}

> Generated: {{generatedAt}}

## Table of Contents
{{#each symbols}}- [{{name}}](#{{slugify name}}) - {{kind}}
{{/each}}

{{#if module.imports.length}}
### Imports
| Source | Specifiers | Type Only |
|--------|------------|-----------|
{{#each module.imports}}| \`{{source}}\` | {{#each specifiers}}\`{{this}}\`{{#unless @last}}, {{/unless}}{{/each}} | {{#if isTypeOnly}}Yes{{else}}No{{/if}} |
{{/each}}
{{/if}}

{{#if module.exports.length}}
### Exports
| Name | Default | Type Only |
|------|---------|-----------|
{{#each module.exports}}| \`{{name}}\` | {{#if isDefault}}Yes{{else}}No{{/if}} | {{#if isTypeOnly}}Yes{{else}}No{{/if}} |
{{/each}}
{{/if}}

## Symbols
{{#each symbols}}
{{> symbolPartial this}}
---
{{/each}}

[Back to Index](./index.md)
`;

/** Template for rendering a single symbol's documentation. */
export const symbolTemplate = `### {{name}}
{{#if deprecated}}
> ⚠️ **Deprecated**{{#if deprecated.since}} since {{deprecated.since}}{{/if}}: {{deprecated.message}}
{{#if deprecated.replacement}}> Use [{{deprecated.replacement}}]({{deprecated.replacement}}) instead.{{/if}}
{{/if}}

**Kind:** \`{{kind}}\`{{#if modifiers.length}} | **Modifiers:** {{#each modifiers}}\`{{this}}\`{{#unless @last}}, {{/unless}}{{/each}}{{/if}}

\`\`\`typescript
{{signature}}
\`\`\`

{{#if summary}}> {{summary}}{{/if}}
{{#if description}}{{description}}{{else}}*No description provided.*{{/if}}

{{#if parameters.length}}
#### Parameters
| Name | Type | Required | Default | Description |
|------|------|----------|---------|-------------|
{{#each parameters}}| \`{{name}}\` | \`{{type.raw}}\` | {{#if optional}}No{{else}}Yes{{/if}} | {{#if defaultValue}}\`{{defaultValue}}\`{{else}}-{{/if}} | {{#if description}}{{description}}{{else}}-{{/if}} |
{{/each}}
{{/if}}

{{#if returnType}}
#### Returns
\`{{returnType.raw}}\`{{#if returnType.reference}} — See: [{{returnType.reference}}]({{returnType.reference}}){{/if}}
{{/if}}

{{#if examples.length}}
#### Examples
{{#each examples}}{{#if title}}**{{title}}**{{/if}}
{{#if description}}{{description}}{{/if}}
\`\`\`{{language}}
{{code}}
\`\`\`
{{#unless validated}}> ⚠️ Not validated{{#if validationError}}: {{validationError}}{{/if}}{{/unless}}
{{/each}}
{{/if}}

{{#if incomingCalls.length}}
#### Called By
{{#each incomingCalls}}- [{{this}}]({{this}})
{{/each}}{{/if}}

{{#if outgoingCalls.length}}
#### Calls
{{#each outgoingCalls}}- [{{this}}]({{this}})
{{/each}}{{/if}}

{{#if references.length}}
#### See Also
{{#each references}}- [{{this}}]({{this}})
{{/each}}{{/if}}

<details><summary>Source</summary>\`{{source.uri}}\` L{{source.range.start.line}}-{{source.range.end.line}}</details>
`;

/** Template for rendering the documentation index page. */
export const indexTemplate = `# Documentation Index

> Generated: {{generatedAt}} | Version: {{workspace.version}}

## Statistics
| Metric | Value |
|--------|-------|
| Modules | {{statistics.totalModules}} |
| Symbols | {{statistics.totalSymbols}} |
| Documented | {{statistics.documentedSymbols}} |
| Coverage | {{statistics.coveragePercent}}% |
| Fresh/Stale | {{statistics.freshModules}}/{{statistics.staleModules}} |

\`[{{progressBar statistics.coveragePercent}}] {{statistics.coveragePercent}}%\`

{{#if statistics.staleModules}}> ⚠️ {{statistics.staleModules}} stale module(s){{/if}}
{{#if statistics.circularDependencies}}> ⚠️ {{statistics.circularDependencies}} circular dependency chain(s){{/if}}

## Modules
{{#each modulesByDirectory}}
### {{directory}}
| Module | Exports | Documented | Status |
|--------|---------|------------|--------|
{{#each modules}}| [{{fileName}}]({{$ref}}) | {{exports}} | {{documented}} | {{freshnessIcon freshness}} |
{{/each}}
{{/each}}

---
*Generated by [GenDocs](https://github.com/gendocs)*
`;

/** Partial template for symbol rendering */
export const symbolPartial = symbolTemplate;

/** Partial template for parameter table row */
export const parameterPartial = `| \`{{name}}\` | \`{{type.raw}}\` | {{#if optional}}No{{else}}Yes{{/if}} | {{#if defaultValue}}\`{{defaultValue}}\`{{else}}-{{/if}} | {{#if description}}{{description}}{{else}}-{{/if}} |`;

/** Partial template for type reference with optional link */
export const typeRefPartial = `{{#if reference}}[{{raw}}]({{reference}}){{else}}\`{{raw}}\`{{/if}}`;

/** Helper function definitions for Handlebars registration. */
export const helperDefinitions = {
    slugify: (text: string): string =>
        text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
    progressBar: (percent: number): string =>
        '█'.repeat(Math.round(percent / 5)) + '░'.repeat(20 - Math.round(percent / 5)),
    freshnessIcon: (status: string): string =>
        ({ fresh: '✅', stale: '⚠️', orphaned: '❌' }[status] ?? '❓'),
} as const;

/** Collection of all default templates */
export const defaultTemplates = {
    module: moduleTemplate,
    symbol: symbolTemplate,
    index: indexTemplate,
    symbolPartial,
    parameterPartial,
    typeRefPartial,
} as const;

/** Type representing available template names */
export type TemplateName = keyof typeof defaultTemplates;
